// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv7bKysaujx3zaKIYW30_uCE5HJ5yngf4',
    appId: '1:303190116171:web:b04e2c69f3da8c94680ace',
    messagingSenderId: '303190116171',
    projectId: 'ditonton-ac6b4',
    authDomain: 'ditonton-ac6b4.firebaseapp.com',
    storageBucket: 'ditonton-ac6b4.appspot.com',
    measurementId: 'G-MTTL5899GB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9VNNURB6i2YEYE3NNp8h9zsJhuz8QqEY',
    appId: '1:303190116171:android:078200d618ed60ad680ace',
    messagingSenderId: '303190116171',
    projectId: 'ditonton-ac6b4',
    storageBucket: 'ditonton-ac6b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmMEcSlMqlBikIeVSjMvVdQG0DW9dNZ5U',
    appId: '1:303190116171:ios:6cef4606f0ee65ab680ace',
    messagingSenderId: '303190116171',
    projectId: 'ditonton-ac6b4',
    storageBucket: 'ditonton-ac6b4.appspot.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
